{
 "title": "Kafka Processing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Register user per minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "consumer_REGISTER" }
   ]
  },
  {
   "title": "Add refund per minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "consumer_REFUND_NEW" }
   ]
  },
  {
   "title": "Done refund per minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "consumer_REFUND_DONE" }
   ]
  },
  {
   "title": "Cancel refund per minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "consumer_REFUND_CANCELED" }
   ]
  },
  {
   "title": "Add order per minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "consumer_ORDER_NEW" }
   ]
  },
  {
   "title": "Done order per minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "targets": [
    { "expr": "consumer_ORDER_DONE" }
   ]
  },
  {
   "title": "Cancel order per minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "targets": [
    { "expr": "consumer_ORDER_CANCELED" }
   ]
  }
 ]
}